3formatfixes
decentralized-identity/peer-did-method-spec pull request #55
Opened 2023-07-11 18:23 UTC by TelegramSam

fixes #50

2023-07-11 18:24 UTC, TelegramSam commented
@dbluhm does this adequately fix your issues?

Note the inclusion of the leading `.` of the method 2 DID string for consistency.

2023-07-11 18:42 UTC, dbluhm requested changes

2023-07-11 18:42 UTC, dbluhm commented on core.html
> +peer-did-method-3 = "did:peer:3" 64*HEXDIG
I think we want something more along the lines of:

```suggestion
peer-did-method-3 = "did:peer:3" transform encnumbasis
transform = "z"
encnumbasis = 46*BASE58BTC
```

2023-07-11 18:53 UTC, dhh1128 approved these changes
This LGTM. I am in favor of merging, and will do so by end of week unless someone objects.

2023-07-12 15:06 UTC, dbluhm commented on core.html
> +                <li>Encode the hash using the base58btc multibase encoding.</li>
To clarify, my suggestion in #50 was to use multibase + multicodec; multibase gives us the `z` on the front of the and the `multicodec` gives us two prefix bytes of `0x12 0x20` which indicate that the data is a sha2-256 hash 32 bytes in length. It's unclear whether that is adequately captured in these changes.

2023-07-17 11:01 UTC, dhh1128 commented
@dbluhm and @TelegramSam : are you ready for this to be merged?

2023-07-17 18:21 UTC, dbluhm commented
I don't think this is ready -- I checked the example Sam used to see if that contained the expected multicodec prefix on the off chance that detail was just missed in the steps to create the DID. The example does not include the multicodec prefix. I think we should be consistent and include the prefix. Beyond just consistency, this leaves the door open for other hash algorithms in the future.

2023-07-31 23:16 UTC, TelegramSam commented
@dbluhm I've fixed this - do me a favor and verify this with code (using my inputs) to see if you get the same results?

2023-08-01 00:17 UTC, dbluhm commented
Verified with this quick program:

```python
import sys
from multiformats import multibase, multihash

value = sys.argv[1]
digest = multihash.digest(value.encode(), "sha2-256")
encoded = multibase.encode(digest, "base58btc")
print(encoded)
```

Looks good to me. Thanks!

2023-08-01 00:17 UTC, dbluhm approved these changes

2023-08-01 07:42 UTC, dhh1128 commented
I'm trying to merge, but github is giving me an unexplained error. I'll check back later and try again; maybe their web server has indigestion.

2023-08-01 07:51 UTC, dhh1128 commented
Doesn't work a few minutes later on a different browser, either... :-(

2023-08-01 08:43 UTC, dhh1128 commented
Still not working, an hour later.

2023-08-12 12:54 UTC, merged

2023-08-12 12:55 UTC, dhh1128 commented
Hooray, it finally merged!